import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import ContentArea from "./components/ContentArea";
// import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "AI Resume Optimization",
  description: "Generated by Luozhonghu, Used by AI to automatically improve resume descriptions.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body className="antialiased">
        {/* 侧边栏 - 固定在左侧 */}
        <Sidebar />
        
        {/* 内容区域 - 占据剩余空间 */}
        <ContentArea>
          {children}
        </ContentArea>
      </body>
    </html>
  );
}
